name: Build and Push latest image

on:
  push:
    # build and push anytime commits are merged to devel
    branches:
      - devel
  schedule:
    # build every 12 hours
    - cron: '0 */12 * * *'

jobs:
  build_and_push_latest:
    runs-on: ubuntu-20.04
    name: Build and push latest tag from devel and on new commits
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Quay login
        run: |
          echo "${{ secrets.QUAY_TOKEN }}" | docker login quay.io -u ${{ secrets.QUAY_USERNAME }} --password-stdin

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          tox -e docker -- --tag=${{ vars.IMAGE_REGISTRY }}/awx-ee:latest

      - name: Push images
        run: |
         docker push ${{ vars.IMAGE_REGISTRY }}/awx-ee:latest
