---

name: CI

on:
  pull_request:
    branches: [devel]

  push:
    branches: [devel]

jobs:
  podman:
    runs-on: ubuntu-20.04
    name: Podman
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build EE with Podman
        run: |
          tox -e podman

  docker:
    runs-on: ubuntu-20.04
    name: Docker
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build EE with Docker
        env:
          DOCKER_BUILDKIT: 1
        run: |
          tox -e docker

  check_diff:
    runs-on: ubuntu-20.04
    name: Ensure build context is up-to-date
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run
        env:
          DOCKER_BUILDKIT: 1
        run: |
          tox -e check-diff
